"""
v0.9 sandbox integration tests — the "between CADCLAW and M3-CRETE for
capability" check the user asked for in the 2026-04-29 session.

Runs all three v0.9 gates against `tests/fixtures/v09_sandbox/v09_assembly.step`
(generated by `tests/generate_v09_sandbox.py`) and asserts the seeded
findings fire as designed:

  - 1 misoriented idler_bracket   → cad.misoriented
  - 1 floating idler              → cad.floating_part
  - 1 cluster of 4 nuts at one end → cluster_parts groups them as one

The sandbox is pure synthetic CadQuery — no M3-CRETE proprietary
geometry, safe to commit and run in CI. If the gates pass on this
sandbox, they're known-good against M3-CRETE-shaped data.

Skips cleanly if the fixture isn't generated (CI without CadQuery
build step won't fail).
"""
from __future__ import annotations

import json
import io
import os
import sys
import unittest
from contextlib import redirect_stdout
from pathlib import Path

from cadclaw_cli.main import main as cli_main

FIXTURES_DIR = Path(__file__).parent / "fixtures" / "v09_sandbox"
STEP = FIXTURES_DIR / "v09_assembly.step"
YAML = FIXTURES_DIR / "cadclaw.yaml"


def _skip_if_missing():
    if not (STEP.exists() and YAML.exists()):
        raise unittest.SkipTest(
            "v0.9 sandbox not generated — run "
            "`python tests/generate_v09_sandbox.py` first"
        )


def _run_harness_json() -> dict:
    """Run `cadclaw harness` against the sandbox and parse the JSON report."""
    buf = io.StringIO()
    with redirect_stdout(buf):
        cli_main([
            "harness",
            "--rules", str(YAML),
            "--report-format", "json",
            "--skip", "publish_audit,claim_audit,bom_audit",
        ])
    return json.loads(buf.getvalue())


class TestSandboxOrientationGate(unittest.TestCase):
    """Gate #1 must flag the one rotated-wrong idler_bracket."""

    def setUp(self):
        _skip_if_missing()

    def test_exactly_one_misorientation_flagged(self):
        d = _run_harness_json()
        misoriented = [f for f in d["findings"]
                       if f["id"] == "cad.misoriented"]
        self.assertEqual(len(misoriented), 1,
                         msg=f"Expected 1 misoriented finding, got "
                             f"{len(misoriented)}: "
                             f"{[f['message'] for f in misoriented]}")
        f = misoriented[0]
        self.assertEqual(f["evidence"]["label"], "idler_bracket")
        self.assertEqual(f["evidence"]["expected_face"], "YZ")
        self.assertEqual(f["evidence"]["expected_axis"], 0)  # X
        self.assertEqual(f["evidence"]["actual_axis"], 1)    # Y
        self.assertIn("about Z", f["suggested_fix"])

    def test_correctly_oriented_brackets_pass_silently(self):
        d = _run_harness_json()
        misoriented = [f for f in d["findings"]
                       if f["id"] == "cad.misoriented"]
        # Two correctly-oriented brackets should NOT be flagged.
        self.assertEqual(len(misoriented), 1)


class TestSandboxFloatingGate(unittest.TestCase):
    """Gate #3 must flag the one floating idler."""

    def setUp(self):
        _skip_if_missing()

    def test_floating_idler_flagged(self):
        d = _run_harness_json()
        floating = [f for f in d["findings"]
                    if f["id"] == "cad.floating_part"]
        self.assertEqual(len(floating), 1,
                         msg=f"Expected 1 floating finding, got "
                             f"{len(floating)}: "
                             f"{[f['message'] for f in floating]}")
        f = floating[0]
        self.assertEqual(f["evidence"]["label"], "idler")
        # Far from anything — distance must exceed max_gap_mm (5.0).
        self.assertGreater(f["evidence"]["nearest_distance_mm"], 5.0)
        self.assertIn("Move toward", f["suggested_fix"])

    def test_attached_idlers_pass_silently(self):
        d = _run_harness_json()
        floating = [f for f in d["findings"]
                    if f["id"] == "cad.floating_part"]
        # Two correctly-attached idlers should NOT be flagged.
        self.assertEqual(len(floating), 1)


class TestSandboxClusterDiagnostic(unittest.TestCase):
    """Gate #7 — `cadclaw inspect cluster` against the sandbox."""

    def setUp(self):
        _skip_if_missing()

    def test_nut_cluster_grouped(self):
        from cadclaw.inspect import cluster_parts, load_parts
        from cadclaw.rules import load_rules
        from cadclaw.inventory import sig as _sig

        rules = load_rules(str(YAML))
        sig_to_label = rules.sig_to_label()

        def label_fn(part):
            d = _sig(part)
            return sig_to_label.get(d, "other")

        parts = load_parts(str(STEP))
        clusters = cluster_parts(parts, label_fn=label_fn,
                                 target_label="nut", radius_mm=50.0)
        # 4 nuts grouped tightly at one end — should form 1 cluster.
        self.assertEqual(len(clusters), 1)
        self.assertEqual(len(clusters[0].members), 4)


class TestSandboxOverall(unittest.TestCase):
    """Headline integration: harness exits with the expected pass/warn/fail."""

    def setUp(self):
        _skip_if_missing()

    def test_gates_listed_in_confidence_budget(self):
        d = _run_harness_json()
        checked = d["confidence_budget"]["checked"]
        self.assertIn("orientation", checked)
        self.assertIn("floating", checked)

    def test_overall_is_fail(self):
        """Both seeded issues are FAIL findings, so overall must be fail."""
        d = _run_harness_json()
        self.assertEqual(d["overall"], "fail")

    def test_total_failure_count_matches_seeded(self):
        """Exactly 2 seeded FAIL findings (1 orientation + 1 floating).

        Other gates (inventory) might add their own findings; this
        assertion is just on the v0.9 gates.
        """
        d = _run_harness_json()
        v09_fails = [f for f in d["findings"]
                     if f["id"] in ("cad.misoriented", "cad.floating_part")]
        self.assertEqual(len(v09_fails), 2)


if __name__ == "__main__":
    unittest.main()
