"""
Scaffold a starter `cadclaw.yaml` from a STEP file (and optional BOM JSON).

This is the v0.6 init-rules path. It is a one-shot script — non-interactive,
write-everything-and-let-the-user-edit. Hand-writing labels for a 50-part
assembly is the adoption bottleneck; this script gets you to a 90% file
in one command.

Usage:
    python examples/init_rules.py --step path/to/assembly.step \\
                                  [--bom path/to/bom.json] \\
                                  [-o cadclaw.yaml]

Heuristic:
  per unique bbox signature, score every BOM item by:
    +3  if BOM item's qty exactly matches the signature's instance count
    +2  if BOM item's name contains a token that resembles a sig dim
        (e.g. "1000mm" matches sig with 1000.0; "NEMA23" matches 56.4 sq)
    +1  if neither, but qty is within +/-2 of count

  Pick top scorer; if confidence (top / second) < 1.5x, write the line as a
  comment so the user reviews it. Belt parts (1.5 x 6.0 cross-section) get
  an explicit `belt_heuristic: true` reminder rather than a guessed label.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Add repo root to path so this script runs without install
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from cadclaw.inventory import load_and_dedup, sig


def _score_bom_item(sig_tuple: Tuple[float, ...], count: int, item: dict) -> int:
    score = 0
    qty = item.get("qty")
    if isinstance(qty, int):
        if qty == count:
            score += 3
        elif abs(qty - count) <= 2:
            score += 1
    name = (item.get("name") or "").lower() + " " + (item.get("description") or "").lower()
    # Look for any sig dimension as a token in the name
    for d in sig_tuple:
        d_str = f"{d:g}"
        if re.search(rf"\b{re.escape(d_str)}\b", name) or f"{int(d)}mm" in name:
            score += 2
            break
    return score


def _pick_label(sig_tuple: Tuple[float, ...], count: int,
                bom_items: List[dict]) -> Tuple[Optional[str], float]:
    """Return (label_guess, confidence_ratio). label_guess None if no BOM."""
    if not bom_items:
        return None, 0.0
    scored: List[Tuple[int, dict]] = []
    for item in bom_items:
        s = _score_bom_item(sig_tuple, count, item)
        if s > 0:
            scored.append((s, item))
    if not scored:
        return None, 0.0
    scored.sort(key=lambda t: t[0], reverse=True)
    top_score, top_item = scored[0]
    second = scored[1][0] if len(scored) > 1 else 0
    name = top_item.get("name", f"item_{top_item.get('id')}")
    label = re.sub(r"[^a-z0-9_]+", "_", name.lower()).strip("_")[:40] or "unnamed"
    confidence = top_score / max(second, 1)
    return label, confidence


def _emit_yaml(step: Path, bom: Optional[Path],
               sig_counts: Counter,
               labels: Dict[Tuple[float, ...], Tuple[str, float, bool]],
               bom_items: List[dict]) -> str:
    """Hand-build the YAML so we can intersperse comments on low-confidence rows."""
    out: List[str] = []
    out.append("# Generated by examples/init_rules.py — REVIEW EVERY LINE.")
    out.append("# Commented label entries are low-confidence guesses.")
    out.append("")
    out.append('schema_version: "0.7"')
    out.append("")
    out.append("meta:")
    out.append(f"  step: {step}")
    if bom:
        out.append(f"  bom: {bom}")
    out.append("")
    out.append("labels:")

    expected: Dict[str, int] = {}
    seen_labels: set = set()
    for sig_tuple, count in sorted(sig_counts.items(), key=lambda kv: -kv[1]):
        label, conf, is_belt = labels.get(sig_tuple, (None, 0.0, False))
        sig_str = f"[{sig_tuple[0]}, {sig_tuple[1]}, {sig_tuple[2]}]"
        if is_belt:
            out.append(f"  # {sig_str}  # belt-shaped cross-section; covered by belt_heuristic")
        elif label is None:
            out.append(f'  # unknown_{sig_tuple[0]}_{sig_tuple[1]}_{sig_tuple[2]}: {sig_str}  # no BOM match (count={count})')
        elif conf < 1.5:
            out.append(f"  # {label}: {sig_str}  # LOW CONFIDENCE (score ratio {conf:.2f}x); count={count}")
        else:
            unique_label = label
            n = 2
            while unique_label in seen_labels:
                unique_label = f"{label}_{n}"
                n += 1
            seen_labels.add(unique_label)
            out.append(f"  {unique_label}: {sig_str}  # count={count}")
            expected[unique_label] = count
    out.append("belt_heuristic: true")
    out.append("")
    out.append("expected_inventory:")
    for label, count in sorted(expected.items()):
        out.append(f"  {label}: {count}")
    out.append("")

    if bom_items:
        out.append("bom_audit:")
        out.append(f"  bom_path: {bom}")
        out.append("  rules:")
        for item in bom_items:
            iid = item.get("id")
            if iid is None:
                continue
            qty = item.get("qty")
            mfg = item.get("mfg_type")
            out.append(f"    - id: {iid}")
            if qty is not None:
                out.append(f"      expected_qty: {qty}")
            if mfg:
                out.append(f"      expected_mfg_type: {mfg}")
            out.append(f"      # name: {item.get('name','?')}")
            out.append(f"      # required_terms: []")
            out.append(f"      # forbidden_terms: []")
        out.append("")

    out.append("claim_audit:")
    out.append("  scan_paths: [README.md]")
    out.append("  stale_terms: []")
    out.append("")
    out.append("publish_audit:")
    out.append("  ignore_globs:")
    out.append('    - ".env*"')
    out.append('    - "bom/orders/**"')
    out.append("  scan_globs:")
    out.append('    - "README.md"')
    out.append("  redact_patterns:")
    out.append("    api_key: 'sk-[A-Za-z0-9]{32,}'")
    out.append("")
    out.append("confidence_budget:")
    out.append("  not_checked:")
    out.append("    - thread engagement (bbox signatures only)")
    out.append("    - native-CAD hidden/suppressed parts")
    out.append("  assumptions:")
    out.append("    - all parts rigid bodies")
    out.append("    - mm units throughout")
    out.append("")
    return "\n".join(out)


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(description="Scaffold cadclaw.yaml from a STEP file.")
    p.add_argument("--step", required=True, help="Path to STEP file.")
    p.add_argument("--bom", default=None, help="Optional BOM JSON file.")
    p.add_argument("-o", "--out", default="cadclaw.yaml")
    args = p.parse_args(argv)

    step = Path(args.step)
    if not step.exists():
        print(f"error: STEP file not found: {step}", file=sys.stderr)
        return 1

    parts = load_and_dedup(str(step))
    sig_counts: Counter = Counter()
    for part in parts:
        s = sig(part)
        sig_counts[s] += 1

    bom_items: List[dict] = []
    if args.bom:
        bom_path = Path(args.bom)
        if not bom_path.exists():
            print(f"error: BOM file not found: {bom_path}", file=sys.stderr)
            return 1
        with bom_path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, list):
            bom_items = data
        elif isinstance(data, dict) and "items" in data:
            bom_items = data["items"]

    labels: Dict[Tuple[float, ...], Tuple[Optional[str], float, bool]] = {}
    for sig_tuple, count in sig_counts.items():
        is_belt = (
            len(sig_tuple) >= 2
            and abs(sig_tuple[0] - 1.5) < 0.01
            and abs(sig_tuple[1] - 6.0) < 0.01
        )
        label, conf = _pick_label(sig_tuple, count, bom_items)
        labels[sig_tuple] = (label, conf, is_belt)

    text = _emit_yaml(step, Path(args.bom) if args.bom else None,
                      sig_counts, labels, bom_items)
    out_path = Path(args.out)
    out_path.write_text(text, encoding="utf-8")

    confident = sum(
        1 for label, conf, is_belt in labels.values()
        if label and conf >= 1.5 and not is_belt
    )
    review = sum(
        1 for label, conf, is_belt in labels.values()
        if (not label or conf < 1.5) and not is_belt
    )
    print(f"Wrote {out_path}: {len(sig_counts)} sigs / {confident} confident / {review} to review.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
